// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: "file:.wrangler/state/v3/d1/miniflare-D1DatabaseObject/ac85c7a0d1e96e35c0a8d1ec24604140939c353ddb91584ae477cb0eddd2e069.sqlite",
  },
});
